@echo off
set arg=%1
set DOCUMENT_NAME=RAPPORT_A17_INFO_ST40_PINARD_MAXIME
echo.
if "%arg%" == "" (
	echo Executing xelatex...
	xelatex %DOCUMENT_NAME% -interaction=batchmode >NUL 2>&1
	echo Executing bibtex...
	bibtex %DOCUMENT_NAME% >NUL 2>&1
	echo Executing makeglossaries...
	makeglossaries %DOCUMENT_NAME% >NUL 2>&1
	echo Executing xelatex...
	xelatex %DOCUMENT_NAME% -interaction=batchmode >NUL 2>&1
	echo Executing xelatex...
	xelatex %DOCUMENT_NAME% -interaction=batchmode >NUL 2>&1
) else (
	echo Executing xelatex...
	xelatex %DOCUMENT_NAME%
	echo Executing bibtex...
	bibtex %DOCUMENT_NAME%
	echo Executing makeglossaries...
	makeglossaries %DOCUMENT_NAME%
	echo Executing xelatex...
	xelatex %DOCUMENT_NAME%
	echo Executing xelatex...
	xelatex %DOCUMENT_NAME%
)
echo.
